### PR TITLE
Create 2023-01-26

### PR DESCRIPTION
**Pull request by lynxworkbot**
@jamsden @berezovskyi I tried to create the minutes but was not allowed to directly create the file. Hence the merge request.

Should I be able to create the minutes directly?

### CODE REVIEW

**Comment by berezovskyi** [comment]
Please relogin, Jad :)

**Comment by jadelkhoury** [comment]
Please ignore. Wrong login.

**Comment by jadelkhoury** [comment]
> Please relogin, Jad :)

Like everything new, the problem is not where you think it is.

**Comment by jadelkhoury** [comment]
@berezovskyi Can you delete the branch? I don't seem to have those rights.

**Comment by berezovskyi** [comment]
@OASIS-OP-Admin can you please give Jad admin rights on the repos now that he is on the PGB?

**Pull request closed without merging**
